spring:
  application:
    name : bookstore

  datasource:
      url: jdbc:mysql://localhost:3306/bookstore
      username: root
      password: zx220904
      driver-class-name: com.mysql.cj.jdbc.Driver

# 服务器配置
server:
  address: 0.0.0.0
  port: 8080

#项目物理地址
base-dir: D:/working/Java/projects/bookstore
path:
  data-dir: ${base-dir}/data
#  pst-dir: ${path.data-dir}/pst #持久数据
#  tmp-dir: ${path.data-dir}/tmp #缓存数据

  image-dir: ${path.data-dir}/images
  upload-dir: ${path.data-dir}/uploads
  log-dir: ${path.data-dir}/logs

jwt:
    secret: njuit
    expiration: 36_000_000

ai:
  gemini:
    type: gemini
    header: x-goog-api-key
    api-key: AIzaSyBQj6L9AZu5krp9elN_XsH15ly7oLELFZs
    api-base-url: https://api-proxy.me/gemini/v1beta/models/gemini-2.5-flash-lite:generateContent
    model: gemini-2.5-flash
    timeout: 30

  silicon-flow:
    type: silicon-flow
    header: Authorization
    api-key: Bearer sk-iqmzvzucfyjeneusfwtdgovyrrywqichshuylhetxtsntiuc
    api-base-url: https://api.siliconflow.cn/v1/chat/completions
    model: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B
    timeout: 30

  ark:
    type: ark
    header: Authorization
    api-key: Bearer 0f54a6fe-42e4-440a-b33f-87955cc04ec8
    api-base-url: https://ark.cn-beijing.volces.com/api/v3/responses
    model: ep-20251205170749-4snxt
    timeout: 30