spring:
  application:
    name : bookstore

  datasource:
      url: jdbc:mysql://localhost:3306/bookstore
      username: root
      password: zx220904
      driver-class-name: com.mysql.cj.jdbc.Driver

# 服务器配置
server:
  address: 0.0.0.0
  port: 8080

#项目物理地址
base-dir: D:\working\Java\projects\bookstore
path:
  data-dir: ${base-dir}/data
  pst-dir: ${data-dir}/pst #持久数据
  tmp-dir: ${data-dir}/tmp #缓存数据

  image-dir: ${pst-dir}/images
  upload-dir: ${tmp-dir}/uploads
  log-dir: ${tmp-dir}/logs

jwt:
    secret: njuit
    expiration: 3600000

ai:
  gemini:
    model: gemini-2.5-flash
    api-base-url: https://api-proxy.me/gemini/v1beta/models/gemini-2.5-flash:generateContent
    api-key: AIzaSyAr93KguZF-tXnvxhJdU7DWd7dmNNeq1wU
    timeout: 30

  silicon-flow:
    api-key: Bearer sk-iqmzvzucfyjeneusfwtdgovyrrywqichshuylhetxtsntiuc
    api-base-url: https://api.siliconflow.cn/v1/chat/completions
    model: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B
    timeout: 30